# Generated by Django 3.2.2 on 2021-05-17 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_app', '0002_auto_20210517_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='slug',
            field=models.SlugField(default=None, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filter',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование фильтра'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='sub_filters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='filter',
            name='text_request',
            field=models.CharField(max_length=200, verbose_name='Поисковый запрос'),
        ),
    ]
