# Generated by Django 3.2.2 on 2021-05-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_auto_20210517_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='filters', to='blog_app.Video'),
        ),
    ]
