# Generated by Django 3.2.2 on 2021-05-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_auto_20210520_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='published_after',
        ),
        migrations.AddField(
            model_name='filter',
            name='time_interval',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
